version: "2.0"
services:
  puppeteer:
    build:
      context: container/puppeteer
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - .:/app
    working_dir: /app
  ruby:
    image: ruby:3.1-rc-slim-buster
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - ${BASEDIR}:/app/downloads
    working_dir: /app
    environment:
      LANG: ${LANG}
      RUBYOPT: -EUTF-8
